#!/bin/ksh
MACHINE=$1 OSREV=$2 FILES=$3
if [ $(id -u) != 0 ]; then echo $0 failed: root is required; exit 0; fi
rm -rf /root/custom
mkdir /root/custom
for file in $FILES; do
  cp $file /root/custom
done  
chown -R root.wheel /root/custom
export DESTDIR=/usr/dest
export RELEASEDIR=/usr/release
cd /etc
cd /usr/src/etc
#time make release
cp $RELEASEDIR/cd${OSREV}.iso ./custom${OSREV}.iso
